# Generated by Django 4.2 on 2024-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='good_products',
            field=models.ManyToManyField(related_name='good_users', to='products.product'),
        ),
    ]
